name: Report a bug
description: Report a problem with Dataiku Headless.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

        Feature request? Please open a [Discussion](https://github.com/dataiku/dataiku-headless/discussions/new/choose) instead.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `dku dataset list -P MYPROJ`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - Dataiku Headless version (run `dku --version`)
        - Python version
        - DSS version
        - OS
      placeholder: |
        Dataiku Headless: 0.4.1
        Python: 3.13.2
        DSS: 14.5.1
        OS: macOS 15.4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or stack traces
      description: Copy and paste any relevant output. This will be automatically formatted.
      render: shell
