#!/usr/bin/env bash
# ==============================================================================
# Wealth Manager FP&A — Monthly New Business Forecast
# DSS Project Setup via dku CLI
#
# Prerequisites:
#   1. dku CLI installed and authenticated (dku auth status)
#   2. CSVs generated by parse_excel.py in scripts/output/
#   3. DSS instance has a managed filesystem connection (default: filesystem_managed)
#
# Usage:
#   ./scripts/setup_project.sh [--profile PROFILE]
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/output"
RECIPE_DIR="$SCRIPT_DIR/recipes"
PROJECT="WM_NEW_BUSINESS"
CONNECTION="filesystem_managed"  # adjust to your DSS connection name
PROFILE_FLAG=""

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --profile|-p) PROFILE_FLAG="--profile $2"; shift 2;;
        *) echo "Unknown arg: $1"; exit 1;;
    esac
done

DKU="dku $PROFILE_FLAG"

echo "◆ Wealth Manager FP&A — DSS Project Setup"
echo "============================================"

# Check prerequisites
if ! command -v dku &>/dev/null; then
    echo "ERROR: dku CLI not found. Install with: uv tool install dku-cli"
    exit 1
fi

if [ ! -f "$OUTPUT_DIR/input_data.csv" ]; then
    echo "ERROR: CSVs not found. Run parse_excel.py first:"
    echo "  python3 $SCRIPT_DIR/parse_excel.py"
    exit 1
fi

echo ""
echo "Phase 1: Create Project"
echo "------------------------"
$DKU project create $PROJECT --name "Wealth Manager - Monthly New Business Forecast" || \
    echo "  (project may already exist, continuing...)"

echo ""
echo "Phase 2: Upload Source Datasets"
echo "--------------------------------"

# Create and upload all 6 source datasets
for ds in input_data lookup_a_asset_growth lookup_b_platform_weight \
          lookup_c_share_of_solution lookup_d_seasonality lookup_e_headcount; do
    echo "  Uploading $ds..."
    $DKU dataset create "$ds" --type UploadedFiles -P $PROJECT 2>/dev/null || true
    $DKU dataset upload "$ds" "$OUTPUT_DIR/${ds}.csv" -P $PROJECT
done

echo ""
echo "Phase 3: Create Intermediate & Output Datasets"
echo "-------------------------------------------------"

# Intermediate datasets for the pipeline
INTERMEDIATE_DS=(
    "input_prepped"          # After adding year/month_num/half_year
    "enriched_a"             # After join with Tab A
    "enriched_ab"            # After join with Tab B
    "enriched_abc"           # After join with Tab C
    "enriched_abcd"          # After join with Tab D
    "enriched_full"          # After join with Tab E (all lookups attached)
    "forecast_detail"        # Final record-level forecast
    "forecast_monthly"       # Monthly totals for dashboard
    "validation_results"     # Validation checks
)

for ds in "${INTERMEDIATE_DS[@]}"; do
    echo "  Creating $ds..."
    $DKU dataset create "$ds" --type Filesystem --connection $CONNECTION -P $PROJECT 2>/dev/null || true
done

echo ""
echo "Phase 4: Create Recipes"
echo "------------------------"

# Recipe 1: Prep input (add derived join columns)
echo "  Creating prep_input recipe..."
$DKU recipe create prep_input \
    --type python \
    --input input_data \
    --output input_prepped \
    -P $PROJECT 2>/dev/null || true
$DKU recipe set-code prep_input -P $PROJECT --code "@$RECIPE_DIR/prep_input.py"

# Recipe 2: Join with Tab A (Asset Price Growth)
echo "  Creating join_asset_growth recipe..."
$DKU recipe create-join join_asset_growth \
    -i input_prepped \
    -i lookup_a_asset_growth \
    --output-ds enriched_a \
    --join-key growth_entity=growth_entity \
    --join-key solution=solution \
    --join-key year=year \
    -P $PROJECT 2>/dev/null || true

# Recipe 3: Join with Tab B (Platform Weighting)
echo "  Creating join_platform_weight recipe..."
$DKU recipe create-join join_platform_weight \
    -i enriched_a \
    -i lookup_b_platform_weight \
    --output-ds enriched_ab \
    --join-key bp_segment=bp_segment \
    --join-key platform=platform \
    --join-key half_year=half_year \
    -P $PROJECT 2>/dev/null || true

# Recipe 4: Join with Tab C (Share of Solution)
echo "  Creating join_share_solution recipe..."
$DKU recipe create-join join_share_solution \
    -i enriched_ab \
    -i lookup_c_share_of_solution \
    --output-ds enriched_abc \
    --join-key concat_key=concat_key \
    --join-key year=year \
    -P $PROJECT 2>/dev/null || true

# Recipe 5: Join with Tab D (Seasonality)
echo "  Creating join_seasonality recipe..."
$DKU recipe create-join join_seasonality \
    -i enriched_abc \
    -i lookup_d_seasonality \
    --output-ds enriched_abcd \
    --join-key channel=channel \
    --join-key year=year \
    --join-key month_num=month_num \
    -P $PROJECT 2>/dev/null || true

# Recipe 6: Join with Tab E (Headcount & Productivity)
echo "  Creating join_headcount recipe..."
$DKU recipe create-join join_headcount \
    -i enriched_abcd \
    -i lookup_e_headcount \
    --output-ds enriched_full \
    --join-key bp_segment=bp_segment \
    --join-key month=month \
    -P $PROJECT 2>/dev/null || true

# Recipe 7: Compute forecast (recursive monthly calculation)
echo "  Creating compute_forecast recipe..."
$DKU recipe create compute_forecast \
    --type python \
    --input enriched_full \
    --output forecast_detail \
    -P $PROJECT 2>/dev/null || true
$DKU recipe add-output compute_forecast --output forecast_monthly -P $PROJECT 2>/dev/null || true
$DKU recipe set-code compute_forecast -P $PROJECT --code "@$RECIPE_DIR/compute_forecast.py"

# Recipe 8: Validate forecast
echo "  Creating validate_forecast recipe..."
$DKU recipe create validate_forecast \
    --type python \
    --input forecast_detail \
    --output validation_results \
    -P $PROJECT 2>/dev/null || true
$DKU recipe set-code validate_forecast -P $PROJECT --code "@$RECIPE_DIR/validate.py"

echo ""
echo "Phase 5: Organize Flow"
echo "-----------------------"

# Create flow zones for visual organization
$DKU flow create-zone "1. Data Ingestion" -P $PROJECT 2>/dev/null || true
$DKU flow create-zone "2. Enrichment" -P $PROJECT 2>/dev/null || true
$DKU flow create-zone "3. Calculation" -P $PROJECT 2>/dev/null || true
$DKU flow create-zone "4. Output & Validation" -P $PROJECT 2>/dev/null || true

echo ""
echo "Phase 6: Build Pipeline"
echo "------------------------"
echo "  Building full pipeline (recursive from validation_results)..."
$DKU job run \
    --target validation_results \
    -P $PROJECT \
    --type RECURSIVE_BUILD \
    --auto-update-schema \
    --wait

echo ""
echo "Phase 7: Verify"
echo "----------------"
echo "  Flow graph:"
$DKU flow graph -P $PROJECT

echo ""
echo "  Validation results:"
$DKU dataset head validation_results -P $PROJECT

echo ""
echo "  Monthly forecast (first 12 months):"
$DKU dataset head forecast_monthly -P $PROJECT

echo ""
echo "◆ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Open DSS UI → Project: $PROJECT"
echo "  2. Check the Flow for visual pipeline"
echo "  3. Create a Dashboard with forecast_monthly + forecast_detail"
echo "  4. Add scenario for scheduled rebuilds"
